song = love.audio.newSource("assets/song1.mp3", "static")
song:play()

return { --f is red, j is blue
    bpm = 150,
    notes = {
        --{time = 2, offset = 200, type = "holdf", note_duration = 0.1},
        {time = 9.5, offset = 200, type = "speciald", note_duration = 0},
        {time = 10.5, offset = 200, type = "speciald", note_duration = 0},
        {time = 11.5, offset = 200, type = "speciald", note_duration = 0},
        {time = 13, offset = 200, type = "speciald", note_duration = 0},
        {time = 14, offset = 200, type = "speciald", note_duration = 0},
        {time = 15.5, offset = 200, type = "speciald", note_duration = 0},
        {time = 16.5, offset = 200, type = "speciald", note_duration = 0}, 
        {time = 15, offset = -200, type = "normalf", note_duration = 0}, --real begins here
        {time = 18, offset = -80 , type = "normalf", note_duration = 0},
        {time = 19, offset = -140 , type = "normalf", note_duration = 0},
        {time = 20, offset = -80, type = "normalf", note_duration = 0},
        {time = 23, offset = -200, type = "specialk", note_duration = 0}, --potential specials these two below!!
        {time = 24, offset = -140, type = "specialk", note_duration = 0},
        {time = 25, offset = -80, type = "normalf", note_duration = 0},
        {time = 26, offset = -140, type = "normalf", note_duration = 0},
        {time = 27, offset = -80, type = "normalf", note_duration = 0},
        {time = 28, offset = -140, type = "normalf", note_duration = 0},
        {time = 30, offset = -80, type = "normalj", note_duration = 0},
        {time = 31, offset = -140, type = "normalj", note_duration = 0},
        {time = 31.6, offset = -80, type = "normalj", note_duration= 0},
        {time = 32, offset = -20, type = "normalj", note_duration = 0},
        {time = 32.5, offset = -140, type = "normalj", note_duration = 0},
        {time = 35, offset = -80, type = "normalf", note_duration = 0},
        {time = 36, offset = -140, type = "normalf", note_duration = 0},
        {time = 37, offset = -140, type = "normalf", note_duration = 0},
        {time = 37.5, offset = -80, type = "normalf", note_duration = 0},
        {time = 38, offset = -20, type = "normalf", note_duration = 0},
        {time = 38.5, offset = 40, type = "normalf", note_duration= 0},
        {time = 39, offset = 60, type = "normalf", note_duration = 0},
        {time = 39.5, offset = 40, type = "normalf", note_duration= 0},
        {time = 47, offset = -80, type = "normalj", note_duration = 0},
        {time = 47.5, offset = -140, type = "normalj", note_duration = 0},
        {time = 48, offset = -80, type = "normalj", note_duration = 0},
        {time = 48.5, offset = -20, type = "normalf", note_duration = 0},
        {time = 49, offset = 40, type = "normalf", note_duration = 0},
        {time = 49.5, offset = -20, type = "normalf", note_duration= 0},
        {time = 52, offset = -80, type = "normalj", note_duration= 0},
        {time = 52.5, offset = -140, type = "normalj", note_duration= 0},
        {time = 53, offset = -80, type = "normalj", note_duration = 0},
        {time = 53.5, offset = -20, type = "normalf", note_duration = 0},
        {time = 54, offset = 40, type = "normalf", note_duration = 0},
        {time = 54.5, offset = -20, type = "normalf", note_duration = 0},
        {time = 55, offset = -80, type = "normalj", note_duration = 0},
        {time = 55.5, offset = -140, type = "normalj", note_duration = 0},
        {time = 56, offset = -200, type = "normalj", note_duration= 0},
        {time = 56.5, offset = -140, type = "normalj", note_duration= 0},
        {time = 57, offset = -80, type = "normalj", note_duration= 0},
        {time = 57.5, offset = -140, type = "normalj", note_duration= 0},
        {time = 58, offset = -80, type = "normalf", note_duration = 0},
        {time = 58.5, offset = -140, type = "normalf", note_duration = 0},
        {time = 59, offset = -200, type = "normalf", note_duration = 0},
        {time = 59.5, offset = -140, type = "normalf", note_duration = 0},
        {time = 60, offset = -200, type = "normalf", note_duration= 0}, --hard part begins here
        {time = 60.5, offset = -140, type = "normalj", note_duration= 0}, 
        {time = 61, offset = -80, type = "normalj", note_duration= 0},
        {time = 61.5, offset = -20, type = "normalj", note_duration= 0},
        {time = 62, offset = 40, type = "normalj", note_duration= 0},
        {time = 62.5, offset = 100, type = "normalj", note_duration= 0},
        {time = 63, offset = 20, type = "normalj", note_duration= 0},
        {time = 63.5, offset = -40, type = "normalj", note_duration= 0},
        {time = 64, offset = -100, type = "normalj", note_duration= 0},
        {time = 64.5, offset = -140, type = "normalf", note_duration= 0},
        {time = 65, offset = 200, type = "normalf", note_duration= 0},
        {time = 65.5, offset = 140, type = "normalf", note_duration= 0},
        {time = 66, offset = 80, type = "normalf", note_duration= 0},
        {time = 66.5, offset = 20, type = "normalf", note_duration= 0}, --another stair after this one
        {time = 68, offset = 100, type = "normalj", note_duration= 0},
        {time = 68.5, offset = 20, type = "normalj", note_duration= 0},
        {time = 69, offset = -40, type = "normalj", note_duration= 0},
        {time = 69.5, offset = -100, type = "normalj", note_duration= 0},
        {time = 70, offset = -40, type = "normalj", note_duration= 0},
        {time = 70.5, offset = -120, type = "normalj", note_duration= 0},
        {time = 71, offset = -200, type = "normalj", note_duration= 0},
        {time = 71.5, offset = -140, type = "normalf", note_duration= 0},
        {time = 72, offset = -80, type = "normalf", note_duration= 0},
        {time = 72.5, offset = -20, type = "normalf", note_duration= 0},
        {time = 73, offset = 40, type = "normalf", note_duration= 0},
        {time = 73.5, offset = 100, type = "normalf", note_duration= 0},
        {time = 74, offset = 20, type = "normalf", note_duration= 0},
        {time = 74.5, offset = 200, type = "normalf", note_duration= 0},
        {time = 74.5, offset = 140, type = "normalj", note_duration= 0},
        {time = 75, offset = 80, type = "normalf", note_duration= 0}, --doubles
        {time = 75, offset = 20, type = "normalj", note_duration= 0},
        {time = 76, offset = -40, type = "normalf", note_duration= 0},
        {time = 76, offset = -100, type = "normalj", note_duration= 0},
        {time = 77, offset = -150, type = "normalf", note_duration= 0},
        {time = 77, offset = -200, type = "normalj", note_duration= 0},
        {time = 78, offset = 140, type = "normalf", note_duration= 0}, --AHOY MATEY
        {time = 78, offset = 200, type = "normalj", note_duration= 0}, --end of hard part i think
        {time = 80, offset = 200, type = "specialk", note_duration= 0},
        {time = 81, offset = 200, type = "specialk", note_duration= 0},
        {time = 82, offset = 200, type = "specialk", note_duration= 0},
        {time = 83, offset = 200, type = "specialk", note_duration= 0},
        {time = 84.5, offset = 200, type = "specialk", note_duration= 0},
        {time = 86, offset = 200, type = "specialk", note_duration= 0},
        {time = 87.5, offset = 200, type = "specialk", note_duration= 0},
        {time = 89, offset = 200, type = "specialk", note_duration= 0},
        {time = 90.5, offset = 200, type = "specialk", note_duration= 0},
        {time = 92, offset = 200, type = "specialk", note_duration= 0},
        {time = 93.5, offset = 200, type = "specialk", note_duration= 0},
        {time = 93.5, offset = -200, type = "normalj", note_duration= 0}, -- 2nd loop
        {time = 95, offset = -80 , type = "normalj", note_duration= 0},
        {time = 96, offset = -140 , type = "normalj", note_duration= 0},
        {time = 97, offset = -80, type = "normalj", note_duration= 0},
        {time = 101, offset = -200, type = "speciald", note_duration= 0}, --potential specials these two below!!
        {time = 102, offset = -140, type = "speciald", note_duration= 0},
        {time = 103, offset = -80, type = "normalf", note_duration= 0},
        {time = 104, offset = -140, type = "normalf", note_duration= 0},
        {time = 105, offset = -80, type = "normalf", note_duration= 0},
        {time = 106, offset = -140, type = "normalf", note_duration= 0},
        {time = 109, offset = -80, type = "normalj", note_duration= 0},
        {time = 110, offset = -140, type = "normalj", note_duration= 0},
        {time = 112, offset = -140, type = "normalf", note_duration= 0},
        {time = 112.5, offset = -80, type = "normalf", note_duration= 0},
        {time = 115, offset = -140, type = "normalj", note_duration= 0},
        {time = 115.5, offset = -80, type = "normalj", note_duration= 0},
        {time = 116, offset = -20, type = "normalj", note_duration= 0},
        {time = 116.5, offset = 40, type = "normalj", note_duration= 0},
        {time = 117, offset = 60, type = "normalj", note_duration= 0},
        {time = 117.5, offset = 40, type = "normalj", note_duration= 0},
        {time = 126, offset = 200, type = "speciald", note_duration= 0},  --doubles!!
        {time = 126, offset = 140, type = "specialk", note_duration= 0},
        {time = 127.5, offset = 200, type = "speciald", note_duration= 0}, 
        {time = 127.5, offset = 140, type = "specialk", note_duration= 0},
        {time = 129, offset = 200, type = "speciald", note_duration= 0}, 
        {time = 129, offset = 140, type = "specialk", note_duration= 0},
        {time = 130.5, offset = 200, type = "speciald", note_duration= 0}, 
        {time = 130.5, offset = 140, type = "specialk", note_duration= 0},
        {time = 131.5, offset = 200, type = "speciald", note_duration= 0},
        {time = 131.5, offset = 140, type = "specialk", note_duration= 0}, --3rd repeat bruh
        {time = 133, offset = -200, type = "speciald", note_duration= 0},
        {time = 133.75, offset = -140, type = "speciald", note_duration= 0}, --new freaky part
        {time = 134.5, offset = -200, type = "speciald", note_duration= 0},
        {time = 135.25, offset = -140, type = "speciald", note_duration= 0},
        {time = 136, offset = 200, type = "specialk", note_duration= 0},
        {time = 136.75, offset = 140, type = "specialk", note_duration= 0},
        {time = 137.5, offset = 200, type = "specialk", note_duration= 0},
        {time = 138.25, offset = 140, type = "specialk", note_duration= 0},
        {time = 142, offset = 200, type = "speciald", note_duration= 0}, 
        {time = 142.75, offset = 140, type = "speciald", note_duration= 0},
        {time = 143.5, offset = 200, type = "speciald", note_duration= 0},
        {time = 144.25, offset = 140, type = "speciald", note_duration= 0},
        {time = 145, offset = 200, type = "specialk", note_duration= 0},
        {time = 145.75, offset = 140, type = "specialk", note_duration= 0},
        {time = 146.5, offset = 200, type = "specialk", note_duration= 0},
    }
}


--negative is up, down is positive
--2.5 beats per second :o
--column things heres