song = love.audio.newSource("assets/song1.mp3", "static")
song:play()
song1duration = song:getDuration()

return { --f is red, j is blue
    bpm = 150,
    notes = {
        --{time = 2, offset = 200, type = "holdf", note_duration = 0.1},
        {time = 9.5, offset = 200, type = "speciald", note_duration = 0},
        {time = 10.5, offset = 200, type = "speciald", note_duration = 0},
        {time = 11.5, offset = 200, type = "speciald", note_duration = 0},
        {time = 13, offset = 200, type = "speciald", note_duration = 0},
        {time = 14, offset = 200, type = "speciald", note_duration = 0},
        {time = 15.5, offset = 200, type = "speciald", note_duration = 0},
        {time = 16.5, offset = 200, type = "speciald", note_duration = 0}, 
        {time = 15, offset = -200, type = "normalf", note_duration = 0}, --real begins here
        {time = 18, offset = -80 , type = "normalf", note_duration = 0},
        {time = 19, offset = -140 , type = "normalf", note_duration = 0},
        {time = 20, offset = -80, type = "normalf", note_duration = 0},
        {time = 23, offset = -200, type = "specialk", note_duration = 0}, --potential specials these two below!!
        {time = 24, offset = -140, type = "specialk", note_duration = 0},
        {time = 25, offset = -80, type = "normalf", note_duration = 0},
        {time = 26, offset = -140, type = "normalf", note_duration = 0},
        {time = 27, offset = -80, type = "normalf", note_duration = 0},
        {time = 28, offset = -140, type = "normalf", note_duration = 0},
        {time = 30, offset = -80, type = "normalj", note_duration = 0},
        {time = 31, offset = -140, type = "normalj", note_duration = 0},
        {time = 31.6, offset = -80, type = "normalj", note_duration= 0},
        {time = 32, offset = -20, type = "normalj", note_duration = 0},
        {time = 32.5, offset = -140, type = "normalj", note_duration = 0},
        {time = 35, offset = -80, type = "normalf", note_duration = 0},
        {time = 36, offset = -140, type = "normalf", note_duration = 0},
        {time = 37, offset = -140, type = "normalf", note_duration = 0},
        {time = 37.5, offset = -80, type = "normalf", note_duration = 0},
        {time = 38, offset = -20, type = "normalf", note_duration = 0},
        {time = 38.5, offset = 40, type = "normalf", note_duration= 0},
        {time = 39, offset = 60, type = "normalf", note_duration = 0},
        {time = 39.5, offset = 40, type = "normalf", note_duration= 0},
        {time = 47, offset = -80, type = "normalj", note_duration = 0},
        {time = 47.5, offset = -140, type = "normalj", note_duration = 0},
        {time = 48, offset = -80, type = "normalj", note_duration = 0},
        {time = 48.5, offset = -20, type = "normalf", note_duration = 0},
        {time = 49, offset = 40, type = "normalf", note_duration = 0},
        {time = 49.5, offset = -20, type = "normalf", note_duration= 0},
        {time = 52, offset = -80, type = "normalj", note_duration= 0},
        {time = 52.5, offset = -140, type = "normalj", note_duration= 0},
        {time = 53, offset = -80, type = "normalj", note_duration = 0},
        {time = 53.5, offset = -20, type = "normalf", note_duration = 0},
        {time = 54, offset = 40, type = "normalf", note_duration = 0},
        {time = 54.5, offset = -20, type = "normalf", note_duration = 0},
        {time = 55, offset = -80, type = "normalj", note_duration = 0},
        {time = 55.5, offset = -140, type = "normalj", note_duration = 0},
        {time = 56, offset = -200, type = "normalj", note_duration= 0},
        {time = 56.5, offset = -140, type = "normalj", note_duration= 0},
        {time = 57, offset = -80, type = "normalj", note_duration= 0},
        {time = 57.5, offset = -140, type = "normalj", note_duration= 0},
        {time = 58, offset = -80, type = "normalf", note_duration = 0},
        {time = 58.5, offset = -140, type = "normalf", note_duration = 0},
        {time = 59, offset = -200, type = "normalf", note_duration = 0},
        {time = 59.5, offset = -140, type = "normalf", note_duration = 0},
        {time = 60, offset = -200, type = "normalf", note_duration= 0}, --hard part begins here
        {time = 60.5, offset = -140, type = "normalj", note_duration= 0}, 
        {time = 61, offset = -80, type = "normalj", note_duration= 0},
        {time = 61.5, offset = -20, type = "normalj", note_duration= 0},
        {time = 62, offset = 40, type = "normalj", note_duration= 0},
        {time = 62.5, offset = 100, type = "normalj", note_duration= 0},
        {time = 63, offset = 20, type = "normalj", note_duration= 0},
        {time = 63.5, offset = -40, type = "normalj", note_duration= 0},
        {time = 64, offset = -100, type = "normalj", note_duration= 0},
        {time = 64.5, offset = -140, type = "normalf", note_duration= 0},
        {time = 65, offset = 200, type = "normalf", note_duration= 0},
        {time = 65.5, offset = 140, type = "normalf", note_duration= 0},
        {time = 66, offset = 80, type = "normalf", note_duration= 0},
        {time = 66.5, offset = 20, type = "normalf", note_duration= 0}, --another stair after this one
        {time = 68, offset = 100, type = "normalj", note_duration= 0},
        {time = 68.5, offset = 20, type = "normalj", note_duration= 0},
        {time = 69, offset = -40, type = "normalj", note_duration= 0},
        {time = 69.5, offset = -100, type = "normalj", note_duration= 0},
        {time = 70, offset = -40, type = "normalj", note_duration= 0},
        {time = 70.5, offset = -120, type = "normalj", note_duration= 0},
        {time = 71, offset = -200, type = "normalj", note_duration= 0},
        {time = 71.5, offset = -140, type = "normalf", note_duration= 0},
        {time = 72, offset = -80, type = "normalf", note_duration= 0},
        {time = 72.5, offset = -20, type = "normalf", note_duration= 0},
        {time = 73, offset = 40, type = "normalf", note_duration= 0},
        {time = 73.5, offset = 100, type = "normalf", note_duration= 0},
        {time = 74, offset = 20, type = "normalf", note_duration= 0},
        {time = 74.5, offset = 200, type = "normalf", note_duration= 0},
        {time = 74.5, offset = 140, type = "normalj", note_duration= 0},
        {time = 75, offset = 80, type = "normalf", note_duration= 0}, --doubles
        {time = 75, offset = 20, type = "normalj", note_duration= 0},
        {time = 76, offset = -40, type = "normalf", note_duration= 0},
        {time = 76, offset = -100, type = "normalj", note_duration= 0},
        {time = 77, offset = -150, type = "normalf", note_duration= 0},
        {time = 77, offset = -200, type = "normalj", note_duration= 0},
        {time = 78, offset = 140, type = "normalf", note_duration= 0}, --AHOY MATEY
        {time = 78, offset = 200, type = "normalj", note_duration= 0}, --end of hard part i think
        {time = 80, offset = 200, type = "specialk", note_duration= 0},
        {time = 81, offset = 200, type = "specialk", note_duration= 0},
        {time = 82, offset = 200, type = "specialk", note_duration= 0},
        {time = 83, offset = 200, type = "specialk", note_duration= 0},
        {time = 84.5, offset = 200, type = "specialk", note_duration= 0},
        {time = 86, offset = 200, type = "specialk", note_duration= 0},
        {time = 87.5, offset = 200, type = "specialk", note_duration= 0},
        {time = 89, offset = 200, type = "specialk", note_duration= 0},
        {time = 90.5, offset = 200, type = "specialk", note_duration= 0},
        {time = 92, offset = 200, type = "specialk", note_duration= 0},
        {time = 93.5, offset = 200, type = "specialk", note_duration= 0},
        {time = 93.5, offset = -200, type = "normalj", note_duration= 0}, -- 2nd loop
        {time = 95, offset = -80 , type = "normalj", note_duration= 0},
        {time = 96, offset = -140 , type = "normalj", note_duration= 0},
        {time = 97, offset = -80, type = "normalj", note_duration= 0},
        {time = 101, offset = -200, type = "speciald", note_duration= 0}, --potential specials these two below!!
        {time = 102, offset = -140, type = "speciald", note_duration= 0},
        {time = 103, offset = -80, type = "normalf", note_duration= 0},
        {time = 104, offset = -140, type = "normalf", note_duration= 0},
        {time = 105, offset = -80, type = "normalf", note_duration= 0},
        {time = 106, offset = -140, type = "normalf", note_duration= 0},
        {time = 109, offset = -80, type = "normalj", note_duration= 0},
        {time = 110, offset = -140, type = "normalj", note_duration= 0},
        {time = 112, offset = -140, type = "normalf", note_duration= 0},
        {time = 112.5, offset = -80, type = "normalf", note_duration= 0},
        {time = 115, offset = -140, type = "normalj", note_duration= 0},
        {time = 115.5, offset = -80, type = "normalj", note_duration= 0},
        {time = 116, offset = -20, type = "normalj", note_duration= 0},
        {time = 116.5, offset = 40, type = "normalj", note_duration= 0},
        {time = 117, offset = 60, type = "normalj", note_duration= 0},
        {time = 117.5, offset = 40, type = "normalj", note_duration= 0},
        {time = 126, offset = 200, type = "speciald", note_duration= 0},  --doubles!!
        {time = 126, offset = 140, type = "specialk", note_duration= 0},
        {time = 127.5, offset = 200, type = "speciald", note_duration= 0}, 
        {time = 127.5, offset = 140, type = "specialk", note_duration= 0},
        {time = 129, offset = 200, type = "speciald", note_duration= 0}, 
        {time = 129, offset = 140, type = "specialk", note_duration= 0},
        {time = 130.5, offset = 200, type = "speciald", note_duration= 0}, 
        {time = 130.5, offset = 140, type = "specialk", note_duration= 0},
        {time = 131.5, offset = 200, type = "speciald", note_duration= 0},
        {time = 131.5, offset = 140, type = "specialk", note_duration= 0}, --3rd repeat bruh
        {time = 133, offset = -200, type = "speciald", note_duration= 0},
        {time = 133.75, offset = -140, type = "speciald", note_duration= 0}, --new freaky part
        {time = 134.5, offset = -200, type = "speciald", note_duration= 0},
        {time = 135.25, offset = -140, type = "speciald", note_duration= 0},
        {time = 136, offset = 200, type = "specialk", note_duration= 0},
        {time = 136.75, offset = 140, type = "specialk", note_duration= 0},
        {time = 137.5, offset = 200, type = "specialk", note_duration= 0},
        {time = 138.25, offset = 140, type = "specialk", note_duration= 0},
        {time = 142, offset = 200, type = "speciald", note_duration= 0}, 
        {time = 142.75, offset = 140, type = "speciald", note_duration= 0},
        {time = 143.5, offset = 200, type = "speciald", note_duration= 0},
        {time = 144.25, offset = 140, type = "speciald", note_duration= 0},
        {time = 145, offset = 200, type = "specialk", note_duration= 0},
        {time = 145.75, offset = 140, type = "specialk", note_duration= 0},
        {time = 147, offset = -200, type = "specialk", note_duration= 0},
        {time = 147.5, offset = -140, type = "specialk", note_duration= 0},
        {time = 148, offset = -200, type = "specialk", note_duration= 0},
        {time = 151, offset = 220, type = "speciald", note_duration= 0},
        {time = 151.5, offset = 160, type = "speciald", note_duration= 0},
        {time = 152, offset = 220, type = "speciald", note_duration= 0},
        {time = 152.5, offset = 160, type = "speciald", note_duration= 0},
        {time = 153, offset = 220, type = "specialk", note_duration= 0},
        {time = 153.5, offset = 160, type = "specialk", note_duration= 0},
        {time = 154, offset = 220, type = "specialk", note_duration= 0},
        {time = 156.5, offset = -200, type = "speciald", note_duration= 0},
        {time = 157, offset = -140, type = "speciald", note_duration= 0},
        {time = 157.5, offset = -200, type = "speciald", note_duration= 0},
        {time = 163.5, offset = -200, type = "normalf", note_duration = 0}, --small new
        {time = 164, offset = -80 , type = "normalf", note_duration = 0},
        {time = 164.5, offset = -140 , type = "normalf", note_duration = 0},
        {time = 165, offset = -80, type = "normalf", note_duration = 0},
        {time = 165.5, offset = -80 , type = "normalj", note_duration = 0},
        {time = 166, offset = -20 , type = "normalj", note_duration = 0},
        {time = 166.5, offset = -80, type = "normalj", note_duration = 0},
        {time = 167.5, offset = -140, type = "normalf", note_duration = 0},
        {time = 171, offset = -80, type = "normalj", note_duration = 0}, --freak
        {time = 172, offset = -20, type = "normalj", note_duration = 0},
        {time = 173, offset = -80, type = "normalj", note_duration = 0},
        {time = 174, offset = -20, type = "normalj", note_duration = 0},
        {time = 175.5, offset = 40, type = "normalf", note_duration = 0},
        {time = 176, offset = 100, type = "normalf", note_duration = 0},
        {time = 176.5, offset = 160, type = "normalf", note_duration = 0},
        {time = 177.5, offset = -200, type = "normalj", note_duration = 0},
        {time = 178, offset = -140, type = "normalj", note_duration = 0},
        {time = 178.5, offset = -200, type = "normalj", note_duration = 0},
        {time = 181, offset = -80, type = "normalf", note_duration = 0}, --freak
        {time = 181.75, offset = -20, type = "normalf", note_duration = 0},
        {time = 182.25, offset = -80, type = "normalf", note_duration = 0},
        {time = 183.25, offset = -20, type = "normalf", note_duration = 0},
        {time = 184, offset = -80, type = "normalf", note_duration = 0},
        {time = 184.5, offset = -20, type = "normalf", note_duration = 0},
        {time = 186, offset = -200, type = "normalj", note_duration = 0},
        {time = 186.5, offset = -140, type = "normalj", note_duration = 0},
        {time = 187, offset = -200, type = "normalj", note_duration = 0},
        {time = 193, offset = 200, type = "specialk", note_duration = 0},
        {time = 193, offset= 140, type = "speciald", note_duration = 0 },
        {time = 194, offset = 200, type = "specialk", note_duration = 0},
        {time = 194, offset= 140, type = "speciald", note_duration = 0 },
        {time = 195, offset = 200, type = "specialk", note_duration = 0},
        {time = 195, offset= 140, type = "speciald", note_duration = 0 },
        {time = 196, offset = 200, type = "specialk", note_duration = 0},
        {time = 196, offset= 140, type = "speciald", note_duration = 0 },
        {time = 197, offset = 200, type = "specialk", note_duration = 0},
        {time = 197, offset= 140, type = "speciald", note_duration = 0 }, --5 notes after ts
        {time = 197.5, offset = -200, type = "normalf", note_duration = 0},
        {time = 198, offset = -140, type = "normalj", note_duration = 0},
        {time = 198.5, offset = -80, type = "normalf", note_duration = 0},
        {time = 199, offset = -20, type = "normalj", note_duration = 0},
        {time = 199.5, offset =  40, type = "normalf", note_duration = 0},
        {time = 200, offset = 100, type = "normalj", note_duration = 0},
        {time = 200, offset = 160, type = "normalf", note_duration = 0},
        {time = 201, offset = -200, type = "normalf", note_duration = 0}, --2nd real
        {time = 203, offset = -80 , type = "normalf", note_duration = 0},
        {time = 204, offset = -140 , type = "normalf", note_duration = 0},
        {time = 205, offset = -80, type = "normalf", note_duration = 0},
        {time = 208, offset = -200, type = "specialk", note_duration = 0}, 
        {time = 209, offset = -140, type = "specialk", note_duration = 0},
        {time = 210, offset = -80, type = "normalf", note_duration = 0},
        {time = 211, offset = -140, type = "normalf", note_duration = 0},
        {time = 212, offset = -80, type = "normalf", note_duration = 0},
        {time = 213, offset = -140, type = "normalf", note_duration = 0},
        {time = 215, offset = -80, type = "normalj", note_duration = 0},
        {time = 216, offset = -140, type = "normalj", note_duration = 0},
        {time = 216.6, offset = -80, type = "normalj", note_duration= 0},
        {time = 217, offset = -20, type = "normalj", note_duration = 0},
        {time = 217.5, offset = -140, type = "normalj", note_duration = 0},
        {time = 220, offset = -80, type = "normalf", note_duration = 0},
        {time = 221, offset = -140, type = "normalf", note_duration = 0},
        {time = 222, offset = -140, type = "normalf", note_duration = 0},
        {time = 222.5, offset = -80, type = "normalf", note_duration = 0},
        {time = 223, offset = -20, type = "normalf", note_duration = 0},
        {time = 223.5, offset = 40, type = "normalf", note_duration= 0},
        {time = 224, offset = 60, type = "normalf", note_duration = 0},
        {time = 224.5, offset = 40, type = "normalf", note_duration= 0},
        {time = 232, offset = -80, type = "normalj", note_duration = 0},
        {time = 232.5, offset = -140, type = "normalj", note_duration = 0},
        {time = 233, offset = -80, type = "normalj", note_duration = 0},
        {time = 233.5, offset = -20, type = "normalf", note_duration = 0},
        {time = 234, offset = 40, type = "normalf", note_duration = 0},
        {time = 234.5, offset = -20, type = "normalf", note_duration= 0},
        {time = 237, offset = -80, type = "normalj", note_duration= 0},
        {time = 237.5, offset = -140, type = "normalj", note_duration= 0},
        {time = 238, offset = -80, type = "normalj", note_duration = 0},
        {time = 238.5, offset = -20, type = "normalf", note_duration = 0},
        {time = 239, offset = 40, type = "normalf", note_duration = 0},
        {time = 239.5, offset = -20, type = "normalf", note_duration = 0},
        {time = 240, offset = -80, type = "normalj", note_duration = 0},
        {time = 240.5, offset = -140, type = "normalj", note_duration = 0},
        {time = 241, offset = -200, type = "normalj", note_duration= 0},
        {time = 241.5, offset = -140, type = "normalj", note_duration= 0},
        {time = 242, offset = -80, type = "normalj", note_duration= 0},
        {time = 242.5, offset = -140, type = "normalj", note_duration= 0},
        {time = 243, offset = -80, type = "normalf", note_duration = 0},
        {time = 243.5, offset = -140, type = "normalf", note_duration = 0},
        {time = 244, offset = -200, type = "normalf", note_duration = 0},
        {time = 244.5, offset = -140, type = "normalf", note_duration = 0},
        {time = 245, offset = -200, type = "normalf", note_duration= 0}, 
        {time = 245.5, offset = -140, type = "normalj", note_duration= 0}, 
        {time = 246, offset = -80, type = "normalj", note_duration= 0},
        {time = 246.5, offset = -20, type = "normalj", note_duration= 0},
        {time = 247, offset = 40, type = "normalj", note_duration= 0},
        {time = 247.5, offset = 100, type = "normalj", note_duration= 0},
        {time = 248, offset = 20, type = "normalj", note_duration= 0},
        {time = 248.5, offset = -40, type = "normalj", note_duration= 0},
        {time = 249, offset = -100, type = "normalj", note_duration= 0},
        {time = 249.5, offset = -140, type = "normalf", note_duration= 0},
        {time = 250, offset = 200, type = "normalf", note_duration= 0},
        {time = 250.5, offset = 140, type = "normalf", note_duration= 0},
        {time = 251, offset = 80, type = "normalf", note_duration= 0},
        {time = 251.5, offset = 20, type = "normalf", note_duration= 0}, --another stair after this one
        {time = 253, offset = 100, type = "normalj", note_duration= 0},
        {time = 253.5, offset = 20, type = "normalj", note_duration= 0},
        {time = 254, offset = -40, type = "normalj", note_duration= 0},
        {time = 254.5, offset = -100, type = "normalj", note_duration= 0},
        {time = 255, offset = -40, type = "normalj", note_duration= 0},
        {time = 255.5, offset = -120, type = "normalj", note_duration= 0},
        {time = 256, offset = -200, type = "normalj", note_duration= 0},
        {time = 256.5, offset = -140, type = "normalf", note_duration= 0},
        {time = 257, offset = -80, type = "normalf", note_duration= 0},
        {time = 257.5, offset = -20, type = "normalf", note_duration= 0},
        {time = 258, offset = 40, type = "normalf", note_duration= 0},
        {time = 258.5, offset = 100, type = "normalf", note_duration= 0},
        {time = 259, offset = 20, type = "normalf", note_duration= 0},
        {time = 259.5, offset = 200, type = "normalf", note_duration= 0},
        {time = 259.5, offset = 140, type = "normalj", note_duration= 0},
        {time = 260, offset = 80, type = "normalf", note_duration= 0}, --doubles
        {time = 260, offset = 20, type = "normalj", note_duration= 0},
        {time = 261, offset = -40, type = "normalf", note_duration= 0},
        {time = 261, offset = -100, type = "normalj", note_duration= 0},
        {time = 262, offset = -150, type = "normalf", note_duration= 0},
        {time = 262, offset = -200, type = "normalj", note_duration= 0},
        {time = 263, offset = 140, type = "normalf", note_duration= 0}, 
        {time = 263, offset = 200, type = "normalj", note_duration= 0},
        {time = 265, offset = 200, type = "specialk", note_duration= 0},
        {time = 266, offset = 200, type = "specialk", note_duration= 0},
        {time = 267, offset = 200, type = "specialk", note_duration= 0},
        {time = 268, offset = 200, type = "specialk", note_duration= 0},
        {time = 269.5, offset = 200, type = "specialk", note_duration= 0},
        {time = 271, offset = 200, type = "specialk", note_duration= 0},
        {time = 272.5, offset = 200, type = "specialk", note_duration= 0},
        {time = 274, offset = 200, type = "specialk", note_duration= 0},
        {time = 275.5, offset = 200, type = "specialk", note_duration= 0},
        {time = 277, offset = 200, type = "specialk", note_duration= 0},
        {time = 278.5, offset = 200, type = "specialk", note_duration= 0},
        {time = 278.5, offset = -200, type = "normalj", note_duration= 0}, -- 2nd loop
        {time = 280, offset = -80 , type = "normalj", note_duration= 0},
        {time = 281, offset = -140 , type = "normalj", note_duration= 0},
        {time = 282, offset = -80, type = "normalj", note_duration= 0},
        {time = 286, offset = -200, type = "speciald", note_duration= 0}, --potential specials these two below!!
        {time = 287, offset = -140, type = "speciald", note_duration= 0},
        {time = 288, offset = -80, type = "normalf", note_duration= 0},
        {time = 289, offset = -140, type = "normalf", note_duration= 0},
        {time = 290, offset = -80, type = "normalf", note_duration= 0},
        {time = 291, offset = -140, type = "normalf", note_duration= 0},
        {time = 294, offset = -80, type = "normalj", note_duration= 0},
        {time = 295, offset = -140, type = "normalj", note_duration= 0},
        {time = 297, offset = -140, type = "normalf", note_duration= 0},
        {time = 297.5, offset = -80, type = "normalf", note_duration= 0},
        {time = 300, offset = -140, type = "normalj", note_duration= 0},
        {time = 300.5, offset = -80, type = "normalj", note_duration= 0},
        {time = 301, offset = -20, type = "normalj", note_duration= 0},
        {time = 301.5, offset = 40, type = "normalj", note_duration= 0},
        {time = 302, offset = 60, type = "normalj", note_duration= 0},
        {time = 302.5, offset = 40, type = "normalj", note_duration= 0},
        {time = 311, offset = 200, type = "speciald", note_duration= 0},  --doubles!!
        {time = 311, offset = 140, type = "specialk", note_duration= 0},
        {time = 312.5, offset = 200, type = "speciald", note_duration= 0}, 
        {time = 312.5, offset = 140, type = "specialk", note_duration= 0},
        {time = 314, offset = 200, type = "speciald", note_duration= 0}, 
        {time = 314, offset = 140, type = "specialk", note_duration= 0},
        {time = 315.5, offset = 200, type = "speciald", note_duration= 0}, 
        {time = 315.5, offset = 140, type = "specialk", note_duration= 0},
        {time = 316.5, offset = 200, type = "speciald", note_duration= 0},
        {time = 316.5, offset = 140, type = "specialk", note_duration= 0}, --3rd repeat bruh
        {time = 318, offset = -200, type = "speciald", note_duration= 0},
        {time = 318.75, offset = -140, type = "speciald", note_duration= 0}, --new freaky part
        {time = 319.5, offset = -200, type = "speciald", note_duration= 0},
        {time = 320.25, offset = -140, type = "speciald", note_duration= 0},
        {time = 321, offset = 200, type = "specialk", note_duration= 0},
        {time = 321.75, offset = 140, type = "specialk", note_duration= 0},
        {time = 322.5, offset = 200, type = "specialk", note_duration= 0},
        {time = 323.25, offset = 140, type = "specialk", note_duration= 0},
        {time = 327, offset = 200, type = "speciald", note_duration= 0}, 
        {time = 327.75, offset = 140, type = "speciald", note_duration= 0},
        {time = 328.5, offset = 200, type = "speciald", note_duration= 0},
        {time = 329.25, offset = 140, type = "speciald", note_duration= 0},
        {time = 330, offset = 200, type = "specialk", note_duration= 0},
        {time = 330.75, offset = 140, type = "specialk", note_duration= 0},
        {time = 332, offset = -200, type = "specialk", note_duration= 0},
        {time = 332.5, offset = -140, type = "specialk", note_duration= 0},
        {time = 333, offset = -200, type = "specialk", note_duration= 0},
        {time = 336, offset = 220, type = "speciald", note_duration= 0},
        {time = 336.5, offset = 160, type = "speciald", note_duration= 0},
        {time = 337, offset = 220, type = "speciald", note_duration= 0},
        {time = 337.5, offset = 160, type = "speciald", note_duration= 0},
        {time = 338, offset = 220, type = "specialk", note_duration= 0},
        {time = 338.5, offset = 160, type = "specialk", note_duration= 0},
        {time = 339, offset = 220, type = "specialk", note_duration= 0},
        {time = 341.5, offset = -200, type = "speciald", note_duration= 0},
        {time = 342, offset = -140, type = "speciald", note_duration= 0},
        {time = 342.5, offset = -200, type = "speciald", note_duration= 0},
        {time = 348.5, offset = -200, type = "normalf", note_duration = 0}, --small new
        {time = 349, offset = -80 , type = "normalf", note_duration = 0},
        {time = 349.5, offset = -140 , type = "normalf", note_duration = 0},
        {time = 350, offset = -80, type = "normalf", note_duration = 0},
        {time = 350.5, offset = -80 , type = "normalj", note_duration = 0},
        {time = 351, offset = -20 , type = "normalj", note_duration = 0},
        {time = 351.5, offset = -80, type = "normalj", note_duration = 0},
        {time = 352.5, offset = -140, type = "normalf", note_duration = 0},
        {time = 356, offset = -80, type = "normalj", note_duration = 0}, --freak
        {time = 357, offset = -20, type = "normalj", note_duration = 0},
        {time = 358, offset = -80, type = "normalj", note_duration = 0},
        {time = 359, offset = -20, type = "normalj", note_duration = 0},
        {time = 360.5, offset = 40, type = "normalf", note_duration = 0},
        {time = 361, offset = 100, type = "normalf", note_duration = 0},
        {time = 361.5, offset = 160, type = "normalf", note_duration = 0},
        {time = 362.5, offset = -200, type = "normalj", note_duration = 0},
        {time = 363, offset = -140, type = "normalj", note_duration = 0},
        {time = 363.5, offset = -200, type = "normalj", note_duration = 0},
        {time = 366, offset = -80, type = "normalf", note_duration = 0}, --freak
        {time = 366.75, offset = -20, type = "normalf", note_duration = 0},
        {time = 367.25, offset = -80, type = "normalf", note_duration = 0},
        {time = 368.25, offset = -20, type = "normalf", note_duration = 0},
        {time = 369, offset = -80, type = "normalf", note_duration = 0},
        {time = 369.5, offset = -20, type = "normalf", note_duration = 0},
        {time = 371, offset = -200, type = "normalj", note_duration = 0},
        {time = 371.5, offset = -140, type = "normalj", note_duration = 0},
        {time = 372, offset = -200, type = "normalj", note_duration = 0},
        {time = 378, offset = 200, type = "specialk", note_duration = 0},
        {time = 378, offset= 140, type = "speciald", note_duration = 0 },
        {time = 379, offset = 200, type = "specialk", note_duration = 0},
        {time = 379, offset= 140, type = "speciald", note_duration = 0 },
        {time = 380, offset = 200, type = "specialk", note_duration = 0},
        {time = 380, offset= 140, type = "speciald", note_duration = 0 },
        {time = 381, offset = 200, type = "specialk", note_duration = 0},
        {time = 381, offset= 140, type = "speciald", note_duration = 0 },
        {time = 382, offset = 200, type = "specialk", note_duration = 0},
        {time = 382, offset = 140, type = "speciald", note_duration = 0},
        {time = 382.5, offset = -200, type = "normalf", note_duration = 0},
        {time = 383, offset = -140, type = "normalj", note_duration = 0},
        {time = 383.5, offset = -80, type = "normalf", note_duration = 0},
        {time = 384, offset = -20, type = "normalj", note_duration = 0},
        {time = 384.5, offset =  40, type = "normalf", note_duration = 0},
        {time = 385, offset = 100, type = "normalj", note_duration = 0},
        {time = 385, offset = 160, type = "normalf", note_duration = 0},
        {time = 386, offset = -200, type = "normalf", note_duration = 0}, --2nd real
        {time = 388, offset = -80 , type = "normalf", note_duration = 0},
        {time = 389, offset = -140 , type = "normalf", note_duration = 0},
        {time = 390, offset = -80, type = "normalf", note_duration = 0},
        {time = 393, offset = -200, type = "specialk", note_duration = 0}, 
        {time = 394, offset = -140, type = "specialk", note_duration = 0},
        {time = 395, offset = -80, type = "normalf", note_duration = 0},
        {time = 396, offset = -140, type = "normalf", note_duration = 0},
        {time = 397, offset = -80, type = "normalf", note_duration = 0},
        {time = 398, offset = -140, type = "normalf", note_duration = 0},
        {time = 400, offset = -80, type = "normalj", note_duration = 0},
        {time = 401, offset = -140, type = "normalj", note_duration = 0},
        {time = 401.6, offset = -80, type = "normalj", note_duration= 0},
        {time = 402, offset = -20, type = "normalj", note_duration = 0},
        {time = 402.5, offset = -140, type = "normalj", note_duration = 0},
        {time = 405, offset = -80, type = "normalf", note_duration = 0},
        {time = 406, offset = -140, type = "normalf", note_duration = 0},
        {time = 407, offset = -140, type = "normalf", note_duration = 0},
        {time = 407.5, offset = -80, type = "normalf", note_duration = 0},
        {time = 408, offset = -20, type = "normalf", note_duration = 0},
        {time = 408.5, offset = 40, type = "normalf", note_duration= 0},
        {time = 409, offset = 60, type = "normalf", note_duration = 0},
        {time = 409.5, offset = 40, type = "normalf", note_duration= 0},
    }
}


--negative is up, down is positive
--2.5 beats per second :o
--column things heres